# Generated by Django 5.2.15 on 2026-06-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0.0)),
                ('bank_logo_painter', models.CharField(default='', max_length=255)),
                ('account_details', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('tax_office', models.CharField(default='', max_length=255)),
                ('tax_number', models.CharField(default='', max_length=50)),
                ('commercial_registry', models.CharField(default='', max_length=50)),
                ('mersis_no', models.CharField(default='', max_length=50)),
                ('address_title', models.CharField(default='', max_length=255)),
                ('address_line1', models.CharField(default='', max_length=255)),
                ('address_line2', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone1', models.CharField(default='', max_length=30)),
                ('phone2', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('status_color_hex', models.CharField(max_length=10)),
                ('status_bg_color_hex', models.CharField(max_length=10)),
                ('location', models.CharField(default='', max_length=255)),
                ('area_sq_meters', models.IntegerField(default=0)),
                ('unit_count', models.IntegerField(default=0)),
                ('shop_count', models.IntegerField(default=0)),
                ('estimated_total_cost', models.FloatField(default=0.0)),
                ('estimated_total_revenue', models.FloatField(default=0.0)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('source_name', models.CharField(default='', max_length=255)),
                ('dest_name', models.CharField(default='', max_length=255)),
                ('contact_name', models.CharField(default='', max_length=255)),
                ('due_date', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
