# Generated by Django 5.2.15 on 2026-06-15 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='base_currency',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='currency',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='document_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='api.account'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='api.account'),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Banka', 'Banka'), ('Nakit', 'Nakit'), ('Borsa', 'Borsa'), ('Kredi Kartı', 'Kredi Kartı'), ('BCH', 'Banka Cari Hesap'), ('Esnek', 'Esnek Hesap')], default='Banka', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='dest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='due_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('supplier', 'Tedarikçi'), ('customer', 'Müşteri'), ('subcontractor', 'Taşeron'), ('government', 'Devlet'), ('bank', 'Banka'), ('other', 'Diğer')], default='other', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('received', 'Alınan'), ('issued', 'Verilen')], default='received', max_length=10)),
                ('status', models.CharField(choices=[('portfolio', 'Portföyde'), ('deposited', 'Tahsile Verildi'), ('cashed', 'Tahsil Edildi'), ('given', 'Ciro/Ödendi'), ('bounced', 'Karşılıksız')], default='portfolio', max_length=12)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3)),
                ('due_date', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('serial_no', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='api.contact')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.contact'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('loan', 'Kredi'), ('kgf', 'KGF'), ('other', 'Diğer')], default='loan', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('principal', models.FloatField(default=0.0)),
                ('total_payable', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('term_months', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='api.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('apartment', 'Daire'), ('shop', 'Dükkan'), ('land', 'Arsa'), ('other', 'Diğer')], default='apartment', max_length=15)),
                ('unit_no', models.CharField(blank=True, default='', max_length=50)),
                ('sale_price', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3)),
                ('sale_date', models.CharField(blank=True, default='', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.contact')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('installment', 'Satış Taksiti'), ('customer', 'Müşteri Alacağı'), ('government', 'Devlet Alacağı'), ('retention', 'Hakediş'), ('other', 'Diğer')], default='customer', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('partial', 'Kısmi Tahsil'), ('collected', 'Tahsil Edildi'), ('overdue', 'Gecikmiş')], default='pending', max_length=12)),
                ('total_amount', models.FloatField(default=0.0)),
                ('collected_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3)),
                ('due_date', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='api.contact')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='api.sale')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('budgeted_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('TRY', '₺ Türk Lirası'), ('USD', '$ Dolar'), ('EUR', '€ Euro')], default='TRY', max_length=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='api.project')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('project', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cost', 'Maliyet'), ('income', 'Gelir')], default='cost', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
