# Generated by Django 5.2.15 on 2026-06-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_existing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
