# Generated by Django 5.2.15 on 2026-06-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_description_project_pafta_project_parsel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='budgetline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='financialtransaction',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receivable',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='currency',
        ),
    ]
