# Generated by Django 5.2.15 on 2026-06-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_account_currency_remove_budgetline_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/'),
        ),
    ]
