# Generated by Django 5.2.15 on 2026-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
