# Generated by Django 5.2.15 on 2026-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projectdocument_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='read_notifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
