# Generated by Django 5.2.15 on 2026-07-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_companyprofile_read_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manuel'), ('recurring_auto', 'Otomatik (Tekrarlayan)')], default='manual', max_length=20),
        ),
    ]
