# Generated by Django 5.2.15 on 2026-07-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_financialtransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='project_images/'),
        ),
    ]
