# Generated by Django 5.2.15 on 2026-07-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_companyprofile_logo_alter_project_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.cheque'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.loan'),
        ),
    ]
