# Generated by Django 5.2.15 on 2026-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_financialtransaction_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='down_payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='installment_count',
            field=models.IntegerField(default=0),
        ),
    ]
